// export const elements = {
//     TEXTBOX: 'TEXTBOX',
//     HEADER: 'HEADER',
//     GRID_LAYOUT_3_3: 'GRID_LAYOUT_3_3',
//     GRID_LAYOUT_1_2: 'GRID_LAYOUT_1_2',
//     MAIN: 'MAIN',
//     FORM:'FORM',
//     TEXT_LAYOUT:'TEXT_LAYOUT',
//   };


export const elements = {
  MAIN:"MAIN",
  HEADER:"HEADER",
  SPAN:"SPAN",
  CONTAINER_GRID_1R1C:"CONTAINER_GRID_1R1C",
  CONTAINER_GRID_1R2C:"CONTAINER_GRID_1R2C",
  CONTAINER_GRID_1R3C:"CONTAINER_GRID_1R3C",
  CONTAINER_GRID_1R4C:"CONTAINER_GRID_1R4C",
  HEADING_TAGS:"HEADING_TAGS",
}